<div class="wrapper">
	 <div class="content-wrapper">
	 	<section class="content">
	 		<div class="row">
	 			<div class="col-xs-12">
	 				<div class="box box-primary">
	 					<div class="box-header with-border">
	 						<h3 class="box-title">Agregar Cargo</h3>
	 					</div>
	 					<form role="form">
	 						<div class="box-body">
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">Nombre</label>
        	 						<input type="nome" class="form-control" placeholder="nombre" id="nombre">
	 							</div>
                                <div class="form-group">
                                	<label for="cargo">Status</label>
                               		<select  id="status" class="form-control" >
                                    	<option value="1">Activo</option>
                                    	<option value="2">Inactivo</option>
                                    </select>
                               </div>
                               <div class="form-group">
	 								<label for="superior">Cargo Superior</label>
	 								<select  id="superior" class="form-control" >
	 									<option value="0">-- Seleccionar --</option>
        	 							<?php 
        	 							foreach ($this->view->cargo as $cargo)
        	 							   {
        	 							       $select .= '<option value="'.$cargo->ID_Cargo.'">'.$cargo->Nombre_Cargo.'</option>';
        	 							   }
        	 							 ?>
        	 							<?php echo($select);?>
        	 						</select>
        	 					</div>
                               <div class="box-footer">
                               <div class="col-xs-6">
                               		<a id="guardar-cargo" class="btn btn-block btn-primary bg-green"><i></i>Guardar</a>
                               </div>
                               <div class="col-xs-6">
                               		<a class="btn btn-block btn-primary bg-red" href="/cargo"><i></i>Cancelar</a>
                               </div>
                               </div>
	 						</div>
	 					</form>
	 				</div>
	 			</div>
	 		</div>
	 	</section>
	 </div>
</div>
<div id="loading-techo"><img src="/loading.gif"></div>

<!-- require Scripts Jquery -->

<script type="text/javascript" src="/assets/js/cargo/cargo.js""></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script>
    $(document).ready(function() {
    	$('#loading-techo').hide();
    });

	$("#guardar-cargo").click(function() {
		$('#loading-techo').show();
		GuardarCargo();
	});
</script>