<div class="wrapper">
	 <div class="content-wrapper">
	 	<section class="content">
	 		<div class="row">
	 			<div class="col-xs-12">
	 				<div class="box box-primary">
	 					<div class="box-header with-border">
	 						<h3 class="box-title">Actualizar Cargo</h3>
	 						<div class="box-body">
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">Nombre</label>
        	 						<input type="nome" class="form-control" placeholder="nombre" id="nombre" value="<?php echo($this->view->cargo->Nombre_Cargo);?>">
	 							</div>
	 							<div class="form-group">
	 								<label for="cargo">Cargo Superior</label>
	 								<select  id="superior" class="form-control" >
	 									<option value="0">-- Seleccionar --</option>
        	 							<?php 
        	 							foreach ($this->view->TodosCargos as $todos)
        	 							   {
        	 							       if($this->view->cargo->ID_Superior == $todos->id)
        	 							       {
        	 							           $select .= '<option selected value="'.$todos->id.'">'.$todos->nombre.'</option>';
        	 							       }
        	 							       else
        	 							       {
        	 							           $select .= '<option value="'.$todos->id.'">'.$todos->nombre.'</option>';
        	 							       }
        	 							   }
        	 							 ?>
        	 							<?php echo($select);?>
        	 						</select>
        	 					</div>
        	 					<div class="form-group">
        	 						<label for="exampleInputEmail1">Cargo Detalle</label>
        	 						<input type="nome" class="form-control" id="detalle" value="<?php echo($this->view->cargo->Detalle_Cargo);?>">
	 							</div>
                                <div class="form-group">
                                <?php 
                                if($this->view->cargo->Status_Cargo== 0)
                                    {
                                        $selecionar = 'selected';
                                    }
                                    
                                    if($this->view->cargo->Status_Cargo== 1)
                                    {
                                        $activo = 'selected';
                                    }
                                    
                                    if($this->view->cargo->Status_Cargo== 2)
                                    {
                                        $inactivo = 'selected';
                                    }
                                ?>
                                	<label for="status">Status</label>
                               		<select  id="status" class="form-control" >
                               			<option <?php echo ($selecionar);?> value="0">-- Seleccionar --</option>
                                    	<option <?php echo ($activo);?> value="1">Activo</option>
                                    	<option <?php echo ($inactivo);?> value="2">Inactivo</option>
                                    </select>
                               </div>
                               <div class="form-group">
                                    <input type="hidden" class="form-control" placeholder="codigo" id="id" value="<?php echo($this->view->cargo->ID_Cargo);?>">
                                </div>
                               <div class="box-footer">
                               <div class="col-xs-6">
                               		<a id="actualizar-cargo" class="btn btn-block btn-primary bg-green"><i></i>Actualizar</a>
                               </div>
                               <div class="col-xs-6">
                               		<a class="btn btn-block btn-primary bg-red" href="/cargo"><i></i>Cancelar</a>
                               </div>
                               </div>
	 						</div>
	 					</form>
	 				</div>
	 			</div>
	 		</div>
	 	</section>
	 </div>
</div>
<div id="loading-techo"><img src="/loading.gif"></div>

<!-- require Scripts Jquery -->

<script type="text/javascript" src="/assets/js/cargo/cargo.js""></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script>
    $(document).ready(function() {
    	$('#loading-techo').hide();
    });

	$("#actualizar-cargo").click(function() {
		$('#loading-techo').show();
		ActualizarCargo();
	});
</script>