<div class="wrapper">
	<div class="content-wrapper">
		<section class="content">
			<div class="row">
				<div class="col-xs-12">
					<div class="box">
						<div class="box-header">
							<h3 class="box-title">Listado Cargos</h3>
							<div class="box-body">
							<a type="button" class="btn btn-primary btn-block btn-padrao bg-green" href="/cargo/add"><i class="fa fa-plus"></i>&nbsp;&nbsp;Agregar Cargo</a></br>
								<table id="listagem" class="table table-bordered table-striped">
									<thead>
										<tr>
											<th>Cargo</th>
											<th>Superior</th>
											<th>Status</th>
											<th></th>
										</tr>
										<tbody>
											 <?php foreach ($this->view->cargo as $cargo):?>
    											 <tr>
        											 <td><?php echo($cargo->Nombre_Cargo);?></td>
        											 <td><?php echo($cargo->Superior_Cargo);?></td>
        											 <td><?php ($cargo->Status_Cargo == '1' ? $cargo->Status_Cargo= 'Activo' : $cargo->Status_Cargo= 'Inactivo'); echo($cargo->Status_Cargo);?></td>
        											 <td>
        											 	<a type="button" href="/cargo/show/<?php echo($cargo->ID_Cargo);?>" class="btn btn-warning bg-yellow"><i class="fa fa-edit"></i></a> 
        											 	<a type="button" href="/cargo/delete/<?php echo($cargo->ID_Cargo);?>" class="btn btn-warning bg-red"><i class="fa fa-trash-o"></i></a>
        											 </td>
        										 </tr>	 
    										 <?php endforeach; ?>
                                        </tbody>
									</thead>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</div>
</div>

<!-- require Scripts Jquery -->

<script type="text/javascript" src="/assets/js/datatables/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/assets/js/datatables/dataTables.bootstrap.min.js"></script>
<script>
  $(function () {
    $('#listagem').DataTable({
      "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
            }
    });
  });
</script>