<div class="wrapper">
	 <div class="content-wrapper">
	 	<section class="content">
	 		<div class="row">
	 			<div class="col-xs-12">
	 				<div class="box box-primary">
	 					<div class="box-header with-border">
	 						<h3 class="box-title">Editar Solicitud</h3>
	 						<div class="box-body">
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">Fecha de Solicitud</label>
        	 						<input type="text" disabled class="form-control" id="fecha_solicitud" value="<?php echo($this->view->correo->fecha_solicitud);?>">
	 							</div>
        	 					<div class="form-group">
        	 						<label for="exampleInputEmail1">email_address</label>
        	 						<input type="text" disabled class="form-control" id="email_address" value="<?php echo($this->view->correo->email_address);?>">
	 							</div>
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">&iquest;Qu&eacute; desea hacer?</label>
        	 						<input type="text" disabled class="form-control" id="hacer" value="<?php echo($this->view->correo->hacer);?>">
	 							</div>
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">Pa&iacute;s</label>
        	 						<input type="text" disabled class="form-control" id="id_pais" value="<?php echo($this->view->correo->nombre_pais);?>">
	 							</div>
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">Motivo de la solicitud</label>
        	 						<input type="text" disabled class="form-control" id="motivo" value="<?php echo($this->view->correo->motivo);?>">
	 							</div>
                               <div class="form-group">
        	 						<label for="exampleInputEmail1">Apellido(s)</label>
        	 						<input type="text" disabled class="form-control" id="apellido" value="<?php echo($this->view->correo->apellido);?>">
	 							</div>
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">Nombre</label>
        	 						<input type="text" disabled class="form-control" id="nombre" value="<?php echo($this->view->correo->nombre);?>">
	 							</div>
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">&iquest;C&oacute;mo le gustaria que fuera su correo?</label>
        	 						<input type="text" disabled class="form-control" id="nuevo_correo" value="<?php echo($this->view->correo->nuevo_correo);?>">
	 							</div>
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">&Aacute;rea</label>
        	 						<input type="text" disabled class="form-control" id="id_area" value="<?php echo($this->view->correo->nombre_area);?>">
	 							</div>
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">Rol</label>
        	 						<input type="text" disabled class="form-control" id="rol" value="<?php echo($this->view->correo->nombre_cargo);?>">
	 							</div>
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">Cuenta real</label>
        	 						<input type="text" disabled class="form-control" id="cuenta_real" value="<?php echo($this->view->correo->cuenta_real);?>">
	 							</div>
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">Alias</label>
        	 						<input type="text" disabled class="form-control" id="alias" value="<?php echo($this->view->correo->alias);?>">
	 							</div>
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">&iquest;Qu&eacute; desea modificar?</label>
        	 						<input type="text" disabled class="form-control" id="modificar" value="<?php echo($this->view->correo->modificar);?>">
	 							</div>
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">Correo a recuperar su contrase&ntilde;a</label>
        	 						<input type="text" disabled class="form-control" id="correo_recuperar_contrasena" value="<?php echo($this->view->correo->correo_recuperar_contrasena);?>">
	 							</div>
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">Correo a suspender</label>
        	 						<input type="text" disabled class="form-control" id="correo_suspender" value="<?php echo($this->view->correo->correo_suspender);?>">
	 							</div>
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">Correo a eliminar</label>
        	 						<input type="text" disabled class="form-control" id="correo_eliminar" value="<?php echo($this->view->correo->correo_eliminar);?>">
	 							</div>
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">&iquest;Deseas transferir los documentos almacenados a otra cuenta?</label>
        	 						<input type="text" disabled class="form-control" id="transferir_documentos" value="<?php echo($this->view->correo->transferir_documentos);?>">
	 							</div>
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">Cuenta de origen</label>
        	 						<input type="text" disabled class="form-control" id="cuenta_origen" value="<?php echo($this->view->correo->cuenta_origen);?>">
	 							</div>
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">Cuenta de destino</label>
        	 						<input type="text" disabled class="form-control" id="cuenta_destino" value="<?php echo($this->view->correo->cuenta_destino);?>">
	 							</div>
	 							<hr style="border-color:red;">
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">contrase&ntilde;a temporal</label>
        	 						<input type="text" disabled class="form-control" id="contrasena_temporal" value="<?php echo($this->view->correo->contrasena_temporal);?>">
	 							</div>
	 							<div class="form-group">
                                <?php 
                                    if($this->view->correo->estado_personas == 1)
                                    {
                                        $aprobado  = 'selected';
                                    }
                                    
                                    if($this->view->correo->estado_personas == 2)
                                    {
                                        $reprobado = 'selected';
                                    }
                                    
                                    if($this->view->correo->estado_personas == 'NULL')
                                    {
                                        $eliger = 'selected';
                                    }
                                ?>
                                	<label for="correo">Estado Personas</label>
                               		<select  id="estado_personas" class="form-control" >
                               			<option <?php echo ($eliger);?> value="NULL">-- Seleccionar --</option>
                                    	<option <?php echo ($aprobado);?> value="1">Aprobado</option>
                                    	<option <?php echo ($reprobado);?> value="2">No Aprobado</option>
                                    </select>
                               </div>
                               <div class="form-group">
                                	<label for="correo">Estado Pyt</label>
                               		<select  id="estado_pyt" class="form-control" >
                               			<option value="0">-- Seleccionar --</option>
                                    	<option value="1">Realizado</option>
                                    	<option value="2">No Realizado</option>
                                    </select>
                               </div>
                               <div class="form-group">
        	 						<label for="exampleInputEmail1">Comentario Pyt</label>
        	 						<input type="text" class="form-control" id="comentario" value="<?php echo($this->view->correo->comentario);?>">
	 							</div>
                               <div class="form-group">
                                    <input type="hidden" class="form-control" placeholder="codigo" id="id" value="<?php echo($this->view->correo->id);?>">
                                </div>
                               <div class="box-footer">
                               <div class="col-xs-6">
                               		<a id="actualizar-correo" class="btn btn-block btn-primary bg-green"><i></i>Actualizar</a>
                               </div>
                               <div class="col-xs-6">
                               		<a class="btn btn-block btn-primary bg-red" href="/correo/listado"><i></i>Cancelar</a>
                               </div>
                               </div>
	 						</div>
	 					</form>
	 				</div>
	 			</div>
	 		</div>
	 	</section>
	 </div>
</div>
<div id="loading-techo"><img src="/loading.gif"></div>

<!-- require Scripts Jquery -->

<script type="text/javascript" src="/assets/js/correo/correo.js""></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script>
    $(document).ready(function() {
    	$('#loading-techo').hide();
    });

	$("#actualizar-correo").click(function() {
		$('#loading-techo').show();
		ActualizarCorreo();
	});
</script>