<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
  		<meta http-equiv="X-UA-Compatible" content="IE=edge">
  		<title>Solicitud de Correo</title>
  		<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  		<link rel="stylesheet" href="/assets/js/bootstrap/css/bootstrap.min.css">
  		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  		<link rel="stylesheet" href="/assets/css/AdminLTE.min.css">
  		<link rel="stylesheet" href="/assets/js/iCheck/square/blue.css">
  		<link rel="stylesheet" type="text/css" href="/assets/css/jquery-confirm.css"/>
  		<link rel="stylesheet" href="/assets/css/custom.css">
	</head>
	<body class="hold-transition">
			<div class="login-logo">
            	<a href="#"><img src="/assets/img/logo-180.jpg"  alt="User Image"></a>
            </div>
            <div class="login-box-body" id="text-1">
            	<p class="login-box-msg"><strong>Solicitud de cuentas TECHO/TETO</strong></p>
            	<strong><p>&#161;Hemos registrado tu respuesta!</p></strong>
            	<strong><p> Te enviaremos un e-mail cuando tu solicitud haya sido procesada.</p></strong>
                <p><strong> Recuerda que las solicitudes:</strong></p>
                <p><strong> * </strong>Se procesan los d&iacute;as MI&Eacute;RCOLES.</p>
                <p><strong> * </strong>El uso de las cuentas se rige por las pol&iacute;ticas especificadas en este documento: <a target="_blank" href="https://docs.google.com/document/d/1dmUoVt0ioJVr9OVKzT1HnT10axE3U7P01Ziz-JrpKT8/edit">Clic Aqu&iacute;</a></p>
                <p><strong> * </strong>Puedes encontrar m&aacute;s informaci&oacute;n y resolver dudas en:  <a target="_blank" href="https://sites.google.com/a/techo.org/intranet/preguntas-frecuentes">Preguntas Frecuentes</a></p>
             </div>
	</body>
</html>
<script src="/assets/js/jQuery/jquery-2.2.3.min.js"></script>
<script src="/assets/js/bootstrap/js/bootstrap.min.js"></script>
<script src="/assets/js/iCheck/icheck.min.js"></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script type="text/javascript" src="/assets/js/correo/correo.js""></script>