<div class="wrapper">
	<div class="content-wrapper">
		<section class="content">
			<div class="row">
				<div class="col-xs-12">
					<div class="box">
						<div class="box-header">
							<h3 class="box-title">Solicitudes de Correos</h3>
							<div class="box-body">
							<a type="button" class="btn btn-primary btn-block btn-padrao bg-green" href="/correo/exportar"><i class="fa fa-file-excel-o"></i>&nbsp;&nbsp;Exportar Solicitud de Creaci&oacute;n</a></br>
								<table id="listagem" class="table table-bordered table-striped">
									<thead>
										<tr>
											<th>Fecha de Solicitud</th>
											<th>Solicitado por</th>
											<th>&iquest;Qu&eacute; desea hacer?</th>
											<th>Nuevo Correo </th>
											<th>Aprobado</th>
											<th></th>
										</tr>
										<tbody>
											 <?php foreach ($this->view->correo as $correo):?>
    											 <tr>
        											 <td><?php echo($correo->fecha_solicitud);?></td>
        											 <td><?php echo($correo->email_address);?></td>
        											 <td><?php echo($correo->hacer);?></td>
        											 <td><?php echo($correo->nuevo_correo);?></td>
        											 <td><?php ($correo->estado_personas == '1' ? $correo->estado_personas = 'S&iacute;' : $correo->estado_personas = 'No'); echo($correo->estado_personas);?></td>
        											 <td>
        											 	<a type="button" title="Editar" href="/correo/show/<?php echo($correo->id);?>" class="btn btn-warning bg-yellow"><i class="fa fa-edit"></i></a> 
        											 	<a type="button" title="Aprobar" href="/correo/aprobado/<?php echo($correo->id);?>" class="btn btn-ok bg-green"><i class="fa fa-check"></i></a>
        											 	<a type="button" title="No Aprobar" href="/correo/reprobado/<?php echo($correo->id);?>" class="btn btn-warning bg-red"><i class="fa fa-trash-o"></i></a>
        											 </td>
        										</tr>	 
    										 <?php endforeach; ?>
                                        </tbody>
									</thead>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</div>
</div>

<!-- require Scripts Jquery -->

<script type="text/javascript" src="/assets/js/datatables/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/assets/js/datatables/dataTables.bootstrap.min.js"></script>
<script>
  $(function () {
    $('#listagem').DataTable({
      "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
            }
    });
  });
</script>