<div class="wrapper">
	<div class="content-wrapper">
		<section class="content">
			<div class="row">
				<div class="col-xs-12">
					<div class="box">
						<div class="box-header">
							<h3 class="box-title">Listado Usuarios</h3>
							<div class="box-body">
								<table id="listagem" class="table table-bordered table-striped">
									<thead>
										<tr>
											<th>Foto</th>
											<th>Usuario</th>
											<th>Email</th>
											<th>&Aacute;rea</th>
											<th>Cargo</th>
											<th>Status</th>
											<th></th>
										</tr>
										<tbody>
											 <?php foreach ($this->view->usuario as $usuario):?>
    											 <tr>
    											  <td align="center"><img class="img-circle-grid" src="<?php session_start(); echo($usuario->Picture_Usuario);?> alt="User Image"></td>
    											 <td><?php echo($usuario->Nombre_Usuario);?></td>
    											 <td><?php echo($usuario->Email_Usuario);?></td>
    											 <td><?php echo($usuario->Area_Usuario);?></td>
    											 <td><?php echo($usuario->Cargo_Usuario);?></td>
    											 <td><?php ($usuario->Status_Usuario == '1' ? $usuario->Status_Usuario = 'Activo' : $usuario->Status_Usuario = 'Inactivo'); echo($usuario->Status_Usuario);?></td>
    											 <td>
    											 	<a type="button" href="/usuario/show/<?php echo($usuario->ID_Usuario);?>" class="btn btn-warning bg-yellow"><i class="fa fa-edit"></i></a> 
    											 	<a type="button" href="/usuario/delete/<?php echo($usuario->ID_Usuario);?>" class="btn btn-warning bg-red"><i class="fa fa-trash-o"></i></a>
    											 </td>
    										 <?php endforeach; ?>
                                        </tbody>
									</thead>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</div>
</div>

<!-- require Scripts Jquery -->

<script type="text/javascript" src="/assets/js/datatables/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/assets/js/datatables/dataTables.bootstrap.min.js"></script>
<script>
  $(function () {
    $('#listagem').DataTable({
      "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
            }
    });
  });
</script>