<div class="wrapper">
	 <div class="content-wrapper">
	 	<section class="content">
	 		<div class="row">
	 			<div class="col-xs-12">
	 				<div class="box box-primary">
	 					<div class="box-header with-border">
	 						<h3 class="box-title">Agregar &Aacute;rea</h3>
	 					</div>
	 					<form role="form">
	 						<div class="box-body">
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">Nombre</label>
        	 						<input type="nome" class="form-control" placeholder="nombre" id="nombre">
	 							</div>
        	 					<div class="form-group">
        	 						<label for="exampleInputPassword1">C&oacute;digo</label>
                                    <input type="codigo" class="form-control" placeholder="codigo" id="codigo">
                                </div>
                                <div class="form-group">
        	 						<label for="exampleInputEmail1">&Aacute;rea Detalle</label>
        	 						<input type="nome" class="form-control" placeholder="detalle" id="detalle">
	 							</div>
                                <div class="form-group">
                                	<label for="area">Status</label>
                               		<select  id="status" class="form-control" >
                                    	<option value="1">Activo</option>
                                    	<option value="2">Inactivo</option>
                                    </select>
                               </div>
                               <div class="box-footer">
                               <div class="col-xs-6">
                               		<a id="guardar-area" class="btn btn-block btn-primary bg-green"><i></i>Guardar</a>
                               </div>
                               <div class="col-xs-6">
                               		<a class="btn btn-block btn-primary bg-red" href="/area"><i></i>Cancelar</a>
                               </div>
                               </div>
	 						</div>
	 					</form>
	 				</div>
	 			</div>
	 		</div>
	 	</section>
	 </div>
</div>
<div id="loading-techo"><img src="/loading.gif"></div>

<!-- require Scripts Jquery -->

<script type="text/javascript" src="/assets/js/area/area.js""></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script>
    $(document).ready(function() {
    	$('#loading-techo').hide();
    });

	$("#guardar-area").click(function() {
		$('#loading-techo').show();
		GuardarArea();
	});
</script>