<div class="wrapper">
	 <div class="content-wrapper">
	 	<section class="content">
	 		<div class="row">
	 			<div class="col-xs-12">
	 				<div class="box box-primary">
	 					<div class="box-header with-border">
	 						<h3 class="box-title">Actualizar Regi&oacute;n</h3>
	 						<div class="box-body">
	 							<div class="form-group">
        	 						<label for="exampleInputEmail1">Nombre</label>
        	 						<input type="nome" class="form-control" placeholder="nombre" id="nombre" value="<?php echo($this->view->region->nombre);?>">
	 							</div>
        	 					<div class="form-group">
        	 						<label for="exampleInputPassword1">C&oacute;digo</label>
                                    <input type="codigo" class="form-control" placeholder="codigo" id="codigo" value="<?php echo($this->view->region->codigo);?>">
                                </div>
                                <div class="form-group">
                                <?php 
                                    if($this->view->region->STATUS == 0)
                                    {
                                        $selecionar = 'selected';
                                    }
                                    
                                    if($this->view->region->STATUS == 1)
                                    {
                                        $activo = 'selected';
                                    }
                                    
                                    if($this->view->region->STATUS == 2)
                                    {
                                        $inactivo = 'selected';
                                    }
                                ?>
                                	<label for="status">Status</label>
                               		<select  id="status" class="form-control" >
                               			<option <?php echo ($selecionar);?> value="0">-- Seleccionar --</option>
                                    	<option <?php echo ($activo);?> value="1">Activo</option>
                                    	<option <?php echo ($inactivo);?> value="2">Inactivo</option>
                                    </select>
                               </div>
                               <div class="form-group">
                                    <input type="hidden" class="form-control" placeholder="codigo" id="id" value="<?php echo($this->view->region->id);?>">
                                </div>
                               <div class="box-footer">
                               <div class="col-xs-6">
                               		<a id="actualizar-region" class="btn btn-block btn-primary bg-green"><i></i>Actualizar</a>
                               </div>
                               <div class="col-xs-6">
                               		<a class="btn btn-block btn-primary bg-red" href="/region"><i></i>Cancelar</a>
                               </div>
                               </div>
	 						</div>
	 					</form>
	 				</div>
	 			</div>
	 		</div>
	 	</section>
	 </div>
</div>
<div id="loading-techo"><img src="/loading.gif"></div>

<!-- require Scripts Jquery -->

<script type="text/javascript" src="/assets/js/region/region.js""></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script>
    $(document).ready(function() {
    	$('#loading-techo').hide();
    });

	$("#actualizar-region").click(function() {
		$('#loading-techo').show();
		ActualizarRegion();
	});
</script>