<div class="wrapper">
	<div class="content-wrapper">
		<section class="content">
			<div class="row">
				<div class="col-xs-12">
					<div class="box">
						<div class="box-header">
							<h3 class="box-title">Listado Sedes</h3>
							<div class="box-body">
								<table id="listagem" class="table table-bordered table-striped">
									<thead>
										<tr>
											<th>Sede</th>
											<th>Pa&iacute;s</th>
											<th>Status</th>
											<th></th>
										</tr>
										<tbody>
											 <?php foreach ($this->view->sede as $sede):?>
    											 <tr>
        											 <td><?php echo($sede->Nombre_Sede);?></td>
        											 <td><?php echo($sede->Pais_Nombre);?></td>
        											 <td><?php ($sede->Status_Sede == '1' ? $sede->Status_Sede = 'Activo' : $sede->Status_Sede = 'Inactivo'); echo($sede->Status_Sede);?></td>
        											 <td>
        											 	<a type="button" href="/sede/show/<?php echo($sede->ID_Sede);?>" class="btn btn-warning bg-yellow"><i class="fa fa-edit"></i></a> 
        											 	<a type="button" onclick="Delete(<?php echo($sede->ID_Sede);?>);" class="btn btn-warning bg-red"><i class="fa fa-trash-o"></i></a>
        											 </td>
        										 </tr>	 
    										 <?php endforeach; ?>
                                        </tbody>
									</thead>
								</table>
								<a class="btn-nuevo" type="button" href="/sede/add"><img src="plus2.png"height="70"></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</div>
</div>

<!-- require Scripts Jquery -->

<script type="text/javascript" src="/assets/js/datatables/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/assets/js/datatables/dataTables.bootstrap.min.js"></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script>
  $(function () {
    $('#listagem').DataTable({
      "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
            }
    });
  });
</script>
<script>
function Delete(id)
{
	var sede = id
    $.confirm({
        content: 'Est\u00E1 seguro de que desea borrar esta Sede',
        buttons: {
            specialKey: {
                text: 'S\u00ED',
                action: function(){
                	window.location.replace("/sede/delete/"+sede);
                }
            },
            alphabet: {
                text: 'No',
                action: function(){
                    return;
                }
            }
        }
    });
}
</script>