<div class="content-wrapper">

    <section class="content">
            <a class="btn btn-app bg-blue" href="/menu_idvirtual" target="_blank">
            	<i class="fa fa-users"></i>Identidad Virtual
           </a>
            <a class="btn btn-app bg-blue" href="http://herramientas.techo.org/aff/ws_soap/" target="_blank">
            	<i class="fa fa-money"></i>Nivel
           </a>
            <a class="btn btn-app bg-blue href="#" target="_blank">
            	<i class="fa fa-balance-scale"></i>Planificaci&oacute;n
           </a>
    </section>

</div>

<div class="control-sidebar-bg"></div>