<div class="content-wrapper">

    <section class="content">
            <a class="btn btn-app bg-blue" href="/pais">
            	<i class="fa fa-globe"></i>Paises
           </a>
           <a class="btn btn-app bg-purple" href="/sede">
            	<i class="fa fa-map-marker"></i>Sedes
           </a>
           <a class="btn btn-app bg-yellow" href="/area">
            	<i class="fa fa-building"></i>Areas
           </a>
           <a class="btn btn-app bg-red" href="/cargo">
            <i class="fa fa-briefcase"></i>Cargos
           </a>
           <a class="btn btn-app bg-green" href="/usuario">
            	<i class="fa fa-users"></i>Usuarios
           </a>
           <a class="btn btn-app bg-gray" href="/correo" target="_blank">
            	<i class="fa fa-envelope-o"></i>Solicitud de Correo
           </a>
           <a class="btn btn-app bg-orange" href="/correo/listado">
            	<i class="fa fa-paper-plane-o"></i>Listado de Correo
           </a>
    </section>

</div>

<div class="control-sidebar-bg"></div>
