<div class="content-wrapper">

    <section class="content">
            <a class="btn btn-app bg-blue" href="#">
            	<i class="fa fa-globe"></i>a&ntilde;adir Pais
           </a>
           <a class="btn btn-app bg-yellow" href="#">
            	<i class="fa fa-building"></i>a&ntilde;adir Area
           </a>
           <a class="btn btn-app bg-red" href="#">
            <i class="fa fa-briefcase"></i>a&ntilde;adir Cargo
          </a>
           <a class="btn btn-app bg-green" href="h#">
            	<i class="fa fa-users"></i> a&ntilde;adir Usuario
           </a>
    </section>

</div>

<div class="control-sidebar-bg"></div>
