<div class="wrapper">
	<div class="content-wrapper">
		<section class="content">
			<div class="row">
				<div class="col-xs-12">
					<div class="box">
						<div class="box-header">
							<h3 class="box-title">Listado Pa&iacute;ses</h3>
							<div class="box-body">
								<table id="listagem" class="table table-bordered table-striped">
									<thead>
										<tr>
											<th>Pa&iacute;s</th>
											<th>C&oacute;digo</th>
											<th>Status</th>
											<th></th>
										</tr>
										<tbody>
											 <?php foreach ($this->view->pais as $pais):?>
    											 <tr>
        											 <td><?php echo($pais->Nombre_Pais);?></td>
        											 <td><?php echo($pais->Codigo_Pais);?></td>
        											 <td><?php ($pais->Status_Pais == '1' ? $pais->Status_Pais = 'Activo' : $pais->Status_Pais = 'Inactivo'); echo($pais->Status_Pais);?></td>
        											 <td>
        											 	<a type="button" href="/pais/show/<?php echo($pais->ID_Pais);?>" class="btn btn-warning bg-yellow"><i class="fa fa-edit"></i></a> 
        											 	<a type="button" onclick="Delete(<?php echo($pais->ID_Pais);?>);" class="btn btn-warning bg-red"><i class="fa fa-trash-o"></i></a>
        											 </td>
        										</tr>	 
    										 <?php endforeach; ?>
                                        </tbody>
									</thead>
								</table>
								 <a class="btn-nuevo" type="button" href="/pais/add"><img src="plus2.png"height="70"></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</div>
</div>

<!-- require Scripts Jquery -->

<script type="text/javascript" src="/assets/js/datatables/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/assets/js/datatables/dataTables.bootstrap.min.js"></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script>
  $(function () {
    $('#listagem').DataTable({
      "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
            }
    });
  });
</script>

<script>
function Delete(id)
{
	var pais = id
    $.confirm({
        content: 'Est\u00E1 seguro de que desea borrar este Pa\u00EDs',
        buttons: {
            specialKey: {
                text: 'S\u00ED',
                action: function(){
                	window.location.replace("/pais/delete/"+pais);
                }
            },
            alphabet: {
                text: 'No',
                action: function(){
                    return;
                }
            }
        }
    });
}
</script>