
CREATE TABLE correo (
   id INT(10) NOT NULL AUTO_INCREMENT,
   fecha_solicitud DATETIME NOT NULL COMMENT 'Timestamp',
   email_address VARCHAR(100) NOT NULL COLLATE utf8_general_ci COMMENT 'persona que solicito correo',
   hacer VARCHAR(100) NOT NULL COLLATE utf8_general_ci COMMENT 'Qué desea hacer',
   id_pais INT(10) NOT NULL COMMENT 'ID Pais',
   apellido VARCHAR(100) DEFAULT NULL COLLATE utf8_general_ci COMMENT 'Apellido',
   nombre VARCHAR(100) DEFAULT NULL COLLATE utf8_general_ci COMMENT 'Nombre',
   nuevo_correo VARCHAR(100) DEFAULT NULL COLLATE utf8_general_ci COMMENT 'Como le gustaria que fuera su correo',
   id_area INT(10) DEFAULT NULL COMMENT 'ID Area',
   id_superior INT(10) DEFAULT NULL COMMENT 'ID Cargo Superior Rol',
   cuenta_real VARCHAR(100) DEFAULT NULL COLLATE utf8_general_ci COMMENT 'Cuenta real',
   alias VARCHAR(100) DEFAULT NULL COLLATE utf8_general_ci COMMENT 'Alias',
   modificar VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci COMMENT 'Que desea modificar',
   correo_recuperar_contrasena VARCHAR(100) DEFAULT NULL COLLATE utf8_general_ci COMMENT 'correo_recuperar_contrasena',
   correo_suspender VARCHAR(100) DEFAULT NULL COLLATE utf8_general_ci COMMENT 'correo suspender',
   correo_eliminar VARCHAR(100) DEFAULT NULL COLLATE utf8_general_ci COMMENT 'correo eliminar',
   transferir_documentos VARCHAR(2) DEFAULT NULL COLLATE utf8_general_ci COMMENT 'Deseas transferir los documentos almacenados a otra cuenta',
   cuenta_origen VARCHAR(100) DEFAULT NULL COLLATE utf8_general_ci COMMENT 'Cuenta de origen',
   cuenta_destino VARCHAR(100) DEFAULT NULL COLLATE utf8_general_ci COMMENT 'Cuenta de destino',
   motivo VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci COMMENT 'Motivo de la solicitud ',
   contrasena_temporal VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci COMMENT 'Correo Contrasena temporal',
   estado_personas VARCHAR(100) DEFAULT NULL COLLATE utf8_general_ci COMMENT 'Estado Personas',
   estado_pyt VARCHAR(100) DEFAULT NULL COLLATE utf8_general_ci COMMENT 'Estado PyT',
   comentario VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci COMMENT 'Comentario',
   id_creador INT(10) UNSIGNED NOT NULL COMMENT 'Id del Creador',
   id_alterador INT(10) UNSIGNED NOT NULL COMMENT 'Id del Alterador',
   fecha_inc DATETIME NOT NULL COMMENT 'Fecha de inclusion del registro',
   fecha_alt DATETIME NOT NULL COMMENT 'fecha de modificacion del registro',
  PRIMARY KEY (id),
  FOREIGN KEY (id_pais) REFERENCES pais (id) ON DELETE CASCADE,
  FOREIGN KEY (id_area) REFERENCES AREA (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci COMMENT='Tabla de las Sedes';