<?php
    $googleClient = new Google_Client();
    $auth = new GoogleAuth($googleClient);
	
	//echo('<pre>');
	//	die(print_r($auth, true));
    
    if($auth->checkRedirectCode())
    {
        header('Location: /home');
    }
?>
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Plataforma de Login | TECHO</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="/assets/js/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href="/assets/css/AdminLTE.min.css">
  <link rel="stylesheet" href="/assets/js/iCheck/square/blue.css">
  <link rel="stylesheet" type="text/css" href="/assets/css/jquery-confirm.css"/>
  <style> 
	@media(max-width: 728px){
		.hide-mobile{
			display:none !important; 
		}
	}
  </style>
</head>
<body class="hold-transition">
	<section>
		<div class="container-fluid">
			 <div class="row">
					<div class="col-12 col-md-8 hide-mobile" style="background-image: url('https://login.techo.org/image-techo.jpg'); min-height: 100vh;">
					</div>
					<div class="col-12 col-md-4" style="background:#fff;">
						<div class="login-box">
							<?php if(!$auth->isLoggedIn()): ?>
									<div class="login-logo">
													<a href="#"><img src="/assets/img/logo-180.jpg"  alt="User Image"></a>
											</div>
												<div class="login-box-body" id="form-login">
													<p class="login-box-msg">Iniciar sesión para acceder al sistema</p>
															<form>
																<div class="row">
																	<div class="">
																		<a type="button" class="btn btn-primary btn-block btn-flat" href="<?php echo $auth->getAuthUrl();?>"><i class="fa fa-google" aria-hidden="true"></i> Ingresa con tu correo TECHO</a>
																	</div>
																</div>
															</form>
												</div>
							<?php else:?>		
								<?php header('Location: /home');?>	
							<?php endif;?>	
								
							</div>
					</div>
			 </div>
		</div>
	
	</section>


<script src="/assets/js/jQuery/jquery-2.2.3.min.js"></script>
<script src="/assets/js/bootstrap/js/bootstrap.min.js"></script>
<script src="/assets/js/iCheck/icheck.min.js"></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script>
$(document).ready(function() {

	var link = window.location.href;
		
	if(link.indexOf("appid") != -1)
	{
		var url   = window.location.search.replace("?", "");
		
		var items = url.split("&");

		var array = {
		  'appid' : items[0],
		  'redirect' : items[1]
		}

		var id = array.appid.split('=');
		var id = id[1]; // appID
		
		var redirect = array.redirect.split('=');
		var redirect = redirect[1]; // Redirect

	 	oData = new Object();	
	 	oData.id       = id;
	 	oData.redirect = redirect;
		
	 	$.ajax({
	 		type: "POST",
	 		url: "/home/save",
	 		dataType: "json",
	 		data: oData,
	 		success: function(oData)
	 		{	
				
	 		}
	 	});
	}
    
});
</script>
</body>
</html>
