<?php
    $googleClient = new Google_Client();
    $auth = new GoogleAuth($googleClient);
    
    if($auth->checkRedirectCode())
    {
        header('Location: /home');
    }
?>
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>ID Virtual | Login</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="/assets/js/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href="/assets/css/AdminLTE.min.css">
  <link rel="stylesheet" href="/assets/js/iCheck/square/blue.css">
  <link rel="stylesheet" type="text/css" href="/assets/css/jquery-confirm.css"/>

</head>
<body class="hold-transition">
<div class="login-box">

<?php if(!$auth->isLoggedIn()): ?>
		<div class="login-logo">
            <a href="#"><img src="/assets/img/logo-180.jpg"  alt="User Image"></a>
        </div>
          <div class="login-box-body" id="form-login">
            <p class="login-box-msg">Iniciar sesión para acceder al sistema</p>
                <form>
                  <div class="row">
                    <div class="">
                      <a type="button" class="btn btn-primary btn-block btn-flat" href="<?php echo $auth->getAuthUrl();?>">Entrar</a>
                    </div>
                  </div>
                </form>
          </div>
<?php else:?>		
	<?php header('Location: /home');?>	
<?php endif;?>	
  
</div>

<script src="/assets/js/jQuery/jquery-2.2.3.min.js"></script>
<script src="/assets/js/bootstrap/js/bootstrap.min.js"></script>
<script src="/assets/js/iCheck/icheck.min.js"></script>
<script type="text/javascript" src="/assets/js/jquery-confirm.js"></script>
<script>
  $(function () {
    $('#esqueci-senha').click(function() {
      $('#form-login').addClass('hide');
      $('#form-esqueci').removeClass('hide');
    });
    $('#voltar-login').click(function() {
      $('#form-login').removeClass('hide');
      $('#form-esqueci').addClass('hide');
    });
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
  
  $( "#btn-esqueci" ).click(function() {
	  EsqueciSenha();
	});
</script>
</body>
</html>
