<?php 
$menu1 = '';
$menu2 = '';

if($_SESSION['user']['area'] != 1)
{
    $menu1 = '<!--';
    $menu2 = '-->';
}

?> 
 <header class="main-header">
      <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
      <link rel="stylesheet" href="/assets/js/bootstrap/css/bootstrap.min.css">
      <link rel="stylesheet" href="/assets/css/AdminLTE.min.css">
      <link rel="stylesheet" href="/assets/css/skins/_all-skins.min.css">
      <link rel="stylesheet" href="/assets/css/custom.css">
      <link rel="stylesheet" href="/assets/css/jquery-confirm.css"/>
      
      <a href="/home" class="logo">
        <img src="/assets/img/novo.jpg"  alt="User Image">
      </a>
      
        <nav class="navbar navbar-static-top">
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
        </nav>
  </header>
  
  <body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
  
  <aside class="main-sidebar">
    <section class="sidebar">
      <div class="user-panel">
        <div class="pull-left image">
            <img class="img-circle" src="<?php session_start(); echo($_SESSION['user']['picture']);?> alt="User Image">
        </div>
        <div class="pull-left info">
          <p><?php session_start(); echo($_SESSION['user']['name']);?></p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <ul class="sidebar-menu">
        <li class="header">MEN&Uacute; NAVEGACI&Oacute;N</li>
        <li class="treeview">
          <a href="/home">
            <i class="fa fa-home"></i> <span>Home</span>
          </a>
        </li>
        <li class="treeview">
          <a href="/correo" target="_blank">
            <i class="fa fa-envelope-o"></i> <span>Solicitud de Correo</span>
          </a>
        </li>
        <?php echo($menu1);?> 
         <li class="treeview">
          <a href="/correo/listado">
            <i class="fa fa-paper-plane-o"></i> <span>Listado de Correo</span>
          </a>
        </li>
         <li class="treeview">
          <a href="/correo/listado">
            <i class="fa fa-history"></i> <span>Historico de Correo</span>
          </a>
        </li>
         <?php echo($menu2);?> 
        <li class="treeview">
          <a href="/pais">
            <i class="fa fa-globe"></i> <span>Catatros de Paises</span>
          </a>
        </li>
        <li class="treeview">
          <a href="/sede">
            <i class="fa fa-map-marker"></i> <span>Catatros de Sedes</span>
          </a>
        </li>
        <li class="treeview">
          <a href="/area">
            <i class="fa fa-building"></i> <span>Catatros de Areas</span>
          </a>
        </li>
        <li class="treeview">
          <a href="/cargo">
            <i class="fa fa-building"></i> <span>Catatros de Cargos</span>
          </a>
        </li>
        <li class="treeview">
          <a href="/usuario">
            <i class="fa fa-group"></i> <span>Catatros de Usuarios</span>
          </a>
        </li>
        <li class="treeview">
          <a href="/logout">
            <i class="fa fa-sign-out"></i> <span>Sair</span>
          </a>
        </li>
      </ul>
    </section>
  </aside>
  
  <script src="/assets/js/jQuery/jquery-2.2.3.min.js"></script>
  <script src="/assets/js/bootstrap/js/bootstrap.min.js"></script>
  <script src="/assets/js/slimScroll/jquery.slimscroll.min.js"></script>
  <script src="/assets/js/fastclick/fastclick.js"></script>
  <script src="/assets/js/app.min.js"></script>