<?php 
$menu1 = '';
$menu2 = '';

if($_SESSION['user']['area'] != 1)
{
    $menu1 = '<!--';
    $menu2 = '-->';
}

?> 
 <header class="main-header">
      <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
      <link rel="stylesheet" href="/assets/js/bootstrap/css/bootstrap.min.css">
      <link rel="stylesheet" href="/assets/css/AdminLTE.min.css">
      <link rel="stylesheet" href="/assets/css/skins/_all-skins.min.css">
      <link rel="stylesheet" href="/assets/css/custom.css">
      <link rel="stylesheet" href="/assets/css/jquery-confirm.css"/>
      <?php 
      if($_SESSION['user']['menu'] == 'skin-blue sidebar-mini sidebar-collapse')
      {
          $logo = " <a href='/home' class='logo'>
          <img src='/mini_techo.jpg' width='20'  alt='User Image'>
          </a>";
      }
      else
      {
         $logo = " <a href='/home' class='logo'>
          <img src='/techo.png' width='170'  alt='User Image'>
          </a>";
      }
      echo($logo);
      ?>
        <nav class="navbar navbar-static-top">
          <a href="#" class="sidebar-toggle" id="menu" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
        </nav>
  </header>
  
  <body class="<?php echo($_SESSION['user']['menu'])?>">
  <div class="wrapper">
  
  <aside class="main-sidebar">
    <section class="sidebar">
      <div class="user-panel">
        <div class="pull-left image">
            <img class="img-circle" src="<?php session_start(); echo($_SESSION['user']['picture']);?> alt="User Image">
        </div>
        <div class="pull-left info">
          <p><?php session_start(); echo($_SESSION['user']['name']);?></p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <ul class="sidebar-menu">
        <li class="header">MEN&Uacute; NAVEGACI&Oacute;N</li>
        <li class="treeview">
          <a href="/home">
            <i class="fa fa-home"></i> <span>Home</span>
          </a>
        </li>
        <li class="treeview">
          <a href="/menu_idvirtual" target="_blank">
            <i class="fa fa-users"></i> <span>Identidad Virtual</span>
          </a>
        </li> 
         	<?php session_start();   foreach ($this->view->apps as $apps):?>
         	<?php if($apps->app == 'Admin Planificacion'){ $hidden = 'hidden';}else{$hidden = '';}?>
         	<?php if($apps->app == 'Calculadora de Puntaje'){$complete = $_SESSION['user']['pais'] . '&token=';}?>
		 	<?php $link .= '<li class="treeview"'.$hidden.'><a href="'.$apps->link . $complete . $_SESSION['user']['token'] . '" target="_blank"> <i class="' .$apps->class . '"></i><span>' . $apps->app . '</span></a></li>';?>
 			<?php endforeach; ?>
 			<?php echo($link)?>
        <li class="treeview">
          <a href="/logout">
            <i class="fa fa-sign-out"></i> <span>Salir</span>
          </a>
        </li>
      </ul>
    </section>
  </aside>
  
  <script src="/assets/js/jQuery/jquery-2.2.3.min.js"></script>
  <script src="/assets/js/bootstrap/js/bootstrap.min.js"></script>
  <script src="/assets/js/slimScroll/jquery.slimscroll.min.js"></script>
  <script src="/assets/js/fastclick/fastclick.js"></script>
  <script src="/assets/js/app.min.js"></script>
<script type="text/javascript" src="/assets/js/menu/menu.js""></script>
  
  <!-- Status Menu -->
  <script>
  $(document).ready(function() {
	  	BuscaStatus();
	  });
  
	$("#menu").click(function() {
		MudaStatus();
	});
</script>