 <header class="main-header">
      <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
      <link rel="stylesheet" href="/assets/js/bootstrap/css/bootstrap.min.css">
      <link rel="stylesheet" href="/assets/css/AdminLTE.min.css">
      <link rel="stylesheet" href="/assets/css/skins/_all-skins.min.css">
      <link rel="stylesheet" href="/assets/css/custom.css">
      <link rel="stylesheet" href="/assets/css/jquery-confirm.css"/>
      
      <a href="/home" class="logo">
        <img src="/assets/img/novo.jpg"  alt="User Image">
      </a>
      
        <nav class="navbar navbar-static-top">
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
        </nav>
  </header>
  
  <body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
  
  <aside class="main-sidebar">
    <section class="sidebar">
      <div class="user-panel">
        <div class="pull-left image">
            <img class="img-circle" src="<?php session_start(); echo($_SESSION['user']['picture']);?> alt="User Image">
        </div>
        <div class="pull-left info">
          <p><?php session_start(); echo($_SESSION['user']['name']);?></p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <ul class="sidebar-menu">
        <li class="header">MEN&Uacute; NAVEGACI&Oacute;N</li>
        <li class="treeview">
          <a href="/home">
            <i class="fa fa-home"></i> <span>Home</span>
          </a>
        </li>
        <li class="treeview">
          <a href="/correo" target="_blank">
            <i class="fa fa-envelope-o"></i> <span>Solicitud de Correo</span>
          </a>
        </li>
         <li class="treeview">
          <a href="#">
            <i class="fa fa-globe"></i>
            <span>Paises</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="/pais"><i class=""></i>Catatros de Paises</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-map-marker"></i>
            <span>Sedes</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="/sede"><i class=""></i>Catatros de Sedes</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-building"></i>
            <span>Areas</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="/area"><i class=""></i>Catatros de Areas</a></li>
          </ul>
        </li>
         <li class="treeview">
          <a href="#">
            <i class="fa fa-briefcase"></i>
            <span>Cargos</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="/cargo"><i class=""></i>Catatros de Cargos</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-group"></i>
            <span>Usuarios</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="/usuario"><i class=""></i>Catatros de Usuarios</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="/logout">
            <i class="fa fa-sign-out"></i> <span>Sair</span>
          </a>
        </li>
      </ul>
    </section>
  </aside>
  
  <script src="/assets/js/jQuery/jquery-2.2.3.min.js"></script>
  <script src="/assets/js/bootstrap/js/bootstrap.min.js"></script>
  <script src="/assets/js/slimScroll/jquery.slimscroll.min.js"></script>
  <script src="/assets/js/fastclick/fastclick.js"></script>
  <script src="/assets/js/app.min.js"></script>